import nodemailer from 'nodemailer';

interface EmailConfig {
  to: string;
  subject: string;
  message: string;
  workflowId?: string;
  actionId?: string;
}

/**
 * Real-time email service using nodemailer
 * Sends actual emails to specified addresses
 */
export class EmailService {
  private transporter: any;
  
  constructor() {
    // Initialize with Gmail SMTP (you can change this to other providers)
    this.transporter = nodemailer.createTransporter({
      service: 'gmail',
      auth: {
        user: process.env.SMTP_EMAIL || 'your-email@gmail.com',
        pass: process.env.SMTP_PASSWORD || 'your-app-password'
      }
    });
  }

  /**
   * Send email notification for workflow events
   */
  async sendWorkflowNotification(config: EmailConfig): Promise<boolean> {
    try {
      const emailHtml = this.generateWorkflowEmail(config);
      
      const mailOptions = {
        from: process.env.SMTP_EMAIL || 'Trading Bot <trading-bot@gmail.com>',
        to: config.to,
        subject: config.subject,
        html: emailHtml,
        text: config.message // Fallback plain text
      };

      console.log(`📧 Sending email to: ${config.to}`);
      console.log(`📝 Subject: ${config.subject}`);
      
      const result = await this.transporter.sendMail(mailOptions);
      
      console.log(`✅ Email sent successfully! Message ID: ${result.messageId}`);
      return true;
      
    } catch (error: any) {
      console.error(`❌ Email send failed:`, error.message);
      return false;
    }
  }

  /**
   * Generate HTML email template for workflow notifications
   */
  private generateWorkflowEmail(config: EmailConfig): string {
    const timestamp = new Date().toLocaleString();
    
    return `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>Trading Workflow Notification</title>
          <style>
            body { 
              font-family: Arial, sans-serif; 
              max-width: 600px; 
              margin: 0 auto; 
              padding: 20px;
              background-color: #f5f5f5;
            }
            .container {
              background: white;
              border-radius: 8px;
              padding: 30px;
              box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            }
            .header {
              background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
              color: white;
              padding: 20px;
              border-radius: 8px;
              margin-bottom: 20px;
              text-align: center;
            }
            .content {
              padding: 20px 0;
            }
            .message {
              background: #f8f9fa;
              border-left: 4px solid #667eea;
              padding: 15px;
              margin: 15px 0;
              border-radius: 4px;
            }
            .footer {
              margin-top: 30px;
              padding-top: 20px;
              border-top: 1px solid #eee;
              font-size: 12px;
              color: #666;
              text-align: center;
            }
            .badge {
              display: inline-block;
              background: #28a745;
              color: white;
              padding: 4px 12px;
              border-radius: 12px;
              font-size: 11px;
              text-transform: uppercase;
              font-weight: bold;
              margin: 5px 0;
            }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1>🚀 Trading Workflow Alert</h1>
              <div class="badge">LIVE NOTIFICATION</div>
            </div>
            
            <div class="content">
              <h2>Workflow Executed Successfully</h2>
              
              <div class="message">
                <strong>📈 Trade Details:</strong><br>
                ${config.message}
              </div>
              
              <p><strong>⏰ Timestamp:</strong> ${timestamp}</p>
              ${config.workflowId ? `<p><strong>🔗 Workflow ID:</strong> <code>${config.workflowId}</code></p>` : ''}
              ${config.actionId ? `<p><strong>⚡ Action ID:</strong> <code>${config.actionId}</code></p>` : ''}
              
              <div style="margin: 20px 0; padding: 15px; background: #e3f2fd; border-radius: 6px;">
                <strong>💡 This is a real-time notification</strong><br>
                Your trading workflow has been executed and this email was sent automatically.
              </div>
            </div>
            
            <div class="footer">
              <p>Generated by Trading Workflow Builder</p>
              <p>Powered by React Flow & Next.js</p>
            </div>
          </div>
        </body>
      </html>
    `;
  }

  /**
   * Test email connectivity
   */
  async testConnection(): Promise<boolean> {
    try {
      await this.transporter.verify();
      console.log('✅ Email service connection verified');
      return true;
    } catch (error: any) {
      console.error('❌ Email service connection failed:', error.message);
      return false;
    }
  }
}

// Singleton instance
export const emailService = new EmailService();